# Generated by Django 4.2.6 on 2023-10-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Apelido', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=100)),
                ('Endereco', models.CharField(max_length=200)),
                ('Numero', models.CharField(max_length=10)),
                ('Complemento', models.CharField(max_length=50)),
                ('Cep', models.CharField(max_length=9)),
                ('Bairro', models.CharField(max_length=100)),
                ('Cidade', models.CharField(max_length=100)),
                ('Estado', models.CharField(max_length=50)),
            ],
        ),
    ]
